import pickle
class_num = {'affenpinscher':1,
                'afghan_hound':2,
                'airedale_terrier':3,
                'akita':4,
                'alaskan_malamute':5,
                'american_eskimo_dog':6,
                'american_foxhound':7,
                'american_staffordshire_terrier':8,
                'american_water_spaniel':9,
                'anatolian_shepherd_dog':10,
                'australian_cattle_dog':11,
                'australian_shepherd':12,
                'australian_terrier':13,
                'basenji':14,
                'basset_hound':15,
                'beagle':16,
                'bearded_collie':17,
                'beauceron':18,
                'bedlington_terrier':19,
                'belgian_malinois':20,
                'belgian_sheepdog':21,
                'belgian_tervuren':22,
                'bernese_mountain_dog':23,
                'bichon_frise':24,
                'black_and_tan_coonhound':25,
                'black_russian_terrier':26,
                'bloodhound':27,
                'bluetick_coonhound':28,
                'border_collie':29,
                'border_terrier':30,
                'borzoi':31,
                'boston_terrier':32,
                'bouvier_des_flandres':33,
                'boxer':34,
                'boykin_spaniel':35,
                'briard':36,
                'brittany':37,
                'brussels_griffon':38,
                'bull_terrier':39,
                'bulldog':40,
                'bullmastiff':41,
                'cairn_terrier':42,
                'canaan_dog':43,
                'cane_corso':44,
                'cardigan_welsh_corgi':45,
                'cavalier_king_charles_spaniel':46,
                'chesapeake_bay_retriever':47,
                'chihuahua':48,
                'chinese_crested':49,
                'chinese_shar-pei':50,
                'chow_chow':51,
                'clumber_spaniel':52,
                'cocker_spaniel':53,
                'collie':54,
                'curly-coated_retriever':55,
                'dachshund':56,
                'dalmatian':57,
                'dandie_dinmont_terrier':58,
                'doberman_pinscher':59,
                'dogue_de_bordeaux':60,
                'english_cocker_spaniel':61,
                'english_setter':62,
                'english_springer_spaniel':63,
                'english_toy_spaniel':64,
                'entlebucher_mountain_dog':65,
                'field_spaniel':66,
                'finnish_spitz':67,
                'flat-coated_retriever':68,
                'french_bulldog':69,
                'german_pinscher':70,
                'german_shepherd_dog':71,
                'german_shorthaired_pointer':72,
                'german_wirehaired_pointer':73,
                'giant_schnauzer':74,
                'glen_of_imaal_terrier':75,
                'golden_retriever':76,
                'gordon_setter':77,
                'great_dane':78,
                'great_pyrenees':79,
                'greater_swiss_mountain_dog':80,
                'greyhound':81,
                'havanese':82,
                'ibizan_hound':83,
                'icelandic_sheepdog':84,
                'irish_red_and_white_setter':85,
                'irish_setter':86,
                'irish_terrier':87,
                'irish_water_spaniel':88,
                'irish_wolfhound':89,
                'italian_greyhound':90,
                'japanese_chin':91,
                'keeshond':92,
                'kerry_blue_terrier':93,
                'komondor':94,
                'kuvasz':95,
                'labrador_retriever':96,
                'lakeland_terrier':97,
                'leonberger':98,
                'lhasa_apso':99,
                'lowchen':100,
                'maltese':101,
                'manchester_terrier':102,
                'mastiff':103,
                'miniature_schnauzer':104,
                'neapolitan_mastiff':105,
                'newfoundland':106,
                'norfolk_terrier':107,
                'norwegian_buhund':108,
                'norwegian_elkhound':109,
                'norwegian_lundehund':110,
                'norwich_terrier':111,
                'nova_scotia_duck_tolling_retriever':112,
                'old_english_sheepdog':113,
                'otterhound':114,
                'papillon':115,
                'parson_russell_terrier':116,
                'pekingese':117,
                'pembroke_welsh_corgi':118,
                'petit_basset_griffon_vendeen':119,
                'pharaoh_hound':120,
                'plott':121,
                'pointer':122,
                'pomeranian':123,
                'poodle':124,
                'portuguese_water_dog':125,
                'saint_bernard':126,
                'silky_terrier':127,
                'smooth_fox_terrier':128,
                'tibetan_mastiff':129,
                'welsh_springer_spaniel':130,
                'wirehaired_pointing_griffon':131,
                'xoloitzcuintli':132,
                'yorkshire_terrier':133,
                'shetland_sheepdog':134,
                'english_foxhound':135,
                'african_hunting_dog':136,
                'dhole':137,
                'dingo':138,
                'mexican_hairless':139,
                'standard_poodle':140,
                'miniature_poodle':140,
                'toy_poodle':141,
                'brabancon_griffon':142,
                'samoyed':143,
                'pug':144,
                'malamute':145,
                'eskimo_dog':146,
                'entleBucher':147,
                'appenzeller':148,
                'miniature_pinscher':149,
                'rottweiler':150,
                'kelpie':151,
                'malinois':152,
                'groenendael':153,
                'schipperke':154,
                'siberian_husky':155,
                'sussex_spaniel':156,
                'vizsla':157,
                'west_Highland_white_terrier':158,
                'scotch_terrier':159,
                'sealyham_terrier':160,
                'irish_terrier':161,
                'shih-Tzu':162,
                'japanese_spaniel':163,
                'redbone':164,
                'walker_hound':165,
                'wire-haired_fox_terrier':166,
                'whippet':167,
                'weimaraner':168,
                'soft-coated_wheaten_terrier':169,
                'staffordshire_bullterrier':170,
                'scottish_deerhound':171,
                'saluki':172,
                'blenheim_spaniel':173,
                'toy_terrier':174,
                'rhodesian_ridgeback':175,
                'standard_schnauzer':176,
                'tibetan_terrier':177,
                'miniature poodle':178,
                'harrier':179,
                'jack russel terrier':180,
                'polish lowland sheepdog':181,
                'dogo argentino':182,
                'miniature bull terrie':183,
                'miniature american eskimo dog':184,
                'puli':185,
                'shiba inu':186,
                'skye terrier':187,
                'spinone italiano':188,
                'swedish vallhund':189,
                'tibetan spaniel':190,
                'toy fox terrier':191,
                'toy manchester terrier':192,
                'welsh terrier':193

}
pickle.dump(class_num, open("save.p", "wb"))

favorite_color = pickle.load(open("save.p", "rb"))
#print(favorite_color)

reversed_dictionary = {value : key for (key, value) in class_num.items()}
pickle.dump(reversed_dictionary, open("breed_dict_reverse.p", "wb"))
    
