import boto3
#s3 = boto3.client('s3')

session = boto3.session.Session()
client = session.client('s3',
                        region_name='sfo2',
                        endpoint_url='https://pmpai.sfo2.digitaloceanspaces.com',
                        aws_access_key_id='DMMTHE4OUKZ2XUYKHHIK',
                        aws_secret_access_key='pxfJEvq63XQ7jYuHAA9BS/QzkwLQae0aG8x9QA3545o')

bucket_name = "pmpai"
directories=['affenpinscher',
                'afghan_hound',
                'airedale_terrier',
                'akita',
                'alaskan_malamute',
                'american_eskimo_dog',
                'american_foxhound',
                'american_staffordshire_terrier',
                'american_water_spaniel',
                'anatolian_shepherd_dog',
                'australian_cattle_dog',
                'australian_shepherd',
                'australian_terrier',
                'basenji',
                'basset_hound',
                'beagle',
                'bearded_collie',
                'beauceron',
                'bedlington_terrier',
                'belgian_malinois',
                'belgian_sheepdog',
                'belgian_tervuren',
                'bernese_mountain_dog',
                'bichon_frise',
                'black_and_tan_coonhound',
                'black_russian_terrier',
                'bloodhound',
                'bluetick_coonhound',
                'border_collie',
                'border_terrier',
                'borzoi',
                'boston_terrier',
                'bouvier_des_flandres',
                'boxer',
                'boykin_spaniel',
                'briard',
                'brittany',
                'brussels_griffon',
                'bull_terrier',
                'bulldog',
                'bullmastiff',
                'cairn_terrier',
                'canaan_dog',
                'cane_corso',
                'cardigan_welsh_corgi',
                'cavalier_king_charles_spaniel',
                'chesapeake_bay_retriever',
                'chihuahua',
                'chinese_crested',
                'chinese_shar-pei',
                'chow_chow',
                'clumber_spaniel',
                'cocker_spaniel',
                'collie',
                'curly-coated_retriever',
                'dachshund',
                'dalmatian',
                'dandie_dinmont_terrier',
                'doberman_pinscher',
                'dogue_de_bordeaux',
                'english_cocker_spaniel',
                'english_setter',
                'english_springer_spaniel',
                'english_toy_spaniel',
                'entlebucher_mountain_dog',
                'field_spaniel',
                'finnish_spitz',
                'flat-coated_retriever',
                'french_bulldog',
                'german_pinscher',
                'german_shepherd_dog',
                'german_shorthaired_pointer',
                'german_wirehaired_pointer',
                'giant_schnauzer',
                'glen_of_imaal_terrier',
                'golden_retriever',
                'gordon_setter',
                'great_dane',
                'great_pyrenees',
                'greater_swiss_mountain_dog',
                'greyhound',
                'havanese',
                'ibizan_hound',
                'icelandic_sheepdog',
                'irish_red_and_white_setter',
                'irish_setter',
                'irish_terrier',
                'irish_water_spaniel',
                'irish_wolfhound',
                'italian_greyhound',
                'japanese_chin',
                'keeshond',
                'kerry_blue_terrier',
                'komondor',
                'kuvasz',
                'labrador_retriever',
                'lakeland_terrier',
                'leonberger',
                'lhasa_apso',
                'lowchen',
                'maltese',
                'manchester_terrier',
                'mastiff',
                'miniature_schnauzer',
                'neapolitan_mastiff',
                'newfoundland',
                'norfolk_terrier',
                'norwegian_buhund',
                'norwegian_elkhound',
                'norwegian_lundehund',
                'norwich_terrier',
                'nova_scotia_duck_tolling_retriever',
                'old_english_sheepdog',
                'otterhound',
                'papillon',
                'parson_russell_terrier',
                'pekingese',
                'pembroke_welsh_corgi',
                'petit_basset_griffon_vendeen',
                'pharaoh_hound',
                'plott',
                'pointer',
                'pomeranian',
                'poodle',
                'portuguese_water_dog',
                'saint_bernard',
                'silky_terrier',
                'smooth_fox_terrier',
                'tibetan_mastiff',
                'welsh_springer_spaniel',
                'wirehaired_pointing_griffon',
                'xoloitzcuintli',
                'yorkshire_terrier',
                'shetland_sheepdog',
                'english_foxhound',
                'african_hunting_dog',
                'dhole',
                'dingo',
                'mexican_hairless',
                'standard_poodle',
                'miniature_poodle',
                'toy_poodle',
                'brabancon_griffon',
                'samoyed',
                'pug',
                'malamute',
                'eskimo_dog',
                'entleBucher',
                'appenzeller',
                'miniature_pinscher',
                'rottweiler',
                'kelpie',
                'malinois',
                'groenendael',
                'schipperke',
                'siberian_husky',
                'sussex_spaniel',
                'vizsla',
                'west_Highland_white_terrier',
                'scotch_terrier',
                'sealyham_terrier',
                'irish_terrier',
                'shih-Tzu',
                'japanese_spaniel',
                'redbone',
                'walker_hound',
                'wire-haired_fox_terrier',
                'whippet',
                'weimaraner',
                'soft-coated_wheaten_terrier',
                'staffordshire_bullterrier',
                'scottish_deerhound',
                'saluki',
                'blenheim_spaniel',
                'toy_terrier',
                'rhodesian_ridgeback',
                'standard_schnauzer',
                'tibetan_terrier',
                'miniature poodle',
                'harrier',
                'jack russel terrier',
                'polish lowland sheepdog',
                'dogo argentino',
                'miniature bull terrie',
                'miniature american eskimo dog',
                'puli',
                'shiba inu',
                'skye terrier',
                'spinone italiano',
                'swedish vallhund',
                'tibetan spaniel',
                'toy fox terrier',
                'toy manchester terrier',
                'welsh terrier'
]
#directory_name = "sample" #it's name of your folders
for directory_name in directories:
    client.put_object(Bucket=bucket_name, Key=(directory_name+'/'))
    
print("Directories Successfully Created")